ice_cream_rating = input('on a scale of zero to ten, how do you enjoy eating icecream?')
sleeping_rating = input('on a scale of zero to ten, how much do you enjoy sleeping?')
first_name = input('input your first name')
print(first_name)
last_name = input('input your last name')
my_name = input('your first and last name')
my_name = print(first_name, last_name)
happiness_rating = input('ice_cream_rating plus sleeping_rating then divide by two')
print(happiness_rating)
type(ice_cream_rating)
type(first_name)
type(happiness_rating)
 print('my name is', my_name, "and i give eating icecream a score of",ice_cream_rating, "out of",10)
 print('I am',my_name ,"and my sleeping enjoyment is", sleeping_rating ,"out of", 10 )
 print('Based on the factors above, my happiness rating is' , happiness_rating, "out of",10)
